param()

$srcDir = $PSScriptRoot
$output = Join-Path (Split-Path $PSScriptRoot -Parent) "bundle.js"

$modules = @(
    "locales-en.js",
    "locales-vi.js",
    "utils.js",
    "models.js",
    "i18n-service.js",
    "controllers\theme.js",
    "controllers\language.js",
    "controllers\nav.js",
    "controllers\skills.js",
    "controllers\career.js",
    "controllers\footer.js",
    "controllers\reveal.js",
    "main.js"
)

$header = @"
/**
 * bundle.js - Auto-generated single-file build (no import/export, no server needed)
 * Offline-friendly: works from file:// protocol on any modern browser.
 *
 * DO NOT EDIT THIS FILE DIRECTLY. Edit source modules in src/bundle/ and
 * regenerate by running: pwsh src/bundle/build.ps1
 */

"@

$parts = @($header)
$totalLines = 0

foreach ($mod in $modules) {
    $modPath = Join-Path $srcDir $mod
    if (-not (Test-Path $modPath)) {
        Write-Error "Module not found: $modPath"
        exit 1
    }

    $content = Get-Content $modPath -Raw
    $modLineCount = ($content -split "`r`n|`n").Count
    $totalLines += $modLineCount

    $divider = ("=" * 60)
    $parts += "// $divider"
    $parts += "// Source: src/bundle/$mod ($modLineCount lines)"
    $parts += "// $divider"
    $parts += ""
    $parts += $content.TrimEnd()
    $parts += ""
}

$divider = ("=" * 60)
$footer = @"
// $divider
// End of bundle.js ($totalLines total lines from $($modules.Count) modules)
// $divider
"@
$parts += $footer

$parts -join "`r`n" | Set-Content $output -NoNewline

Write-Host "bundle.js generated: $output ($totalLines lines from $($modules.Count) modules)"
