#!/bin/bash
# build.sh - Bash-equivalent bundle generator for Linux environments
set -e

SRC_DIR="$(dirname "$0")"
OUTPUT="$SRC_DIR/../bundle.js"

MODULES=(
    "locales-en.js"
    "locales-vi.js"
    "utils.js"
    "models.js"
    "i18n-service.js"
    "controllers/theme.js"
    "controllers/language.js"
    "controllers/nav.js"
    "controllers/skills.js"
    "controllers/career.js"
    "controllers/footer.js"
    "controllers/reveal.js"
    "controllers/hero.js"
    "controllers/about.js"
    "controllers/boot-splash.js"
    "controllers/achievements.js"
    "controllers/achievements-dialog.js"
    "controllers/easter-egg.js"
    "controllers/konami.js"
    "controllers/404-trigger.js"
    "controllers/vim-trap.js"
    "controllers/fine-trigger.js"
    "controllers/red-pill.js"
    "controllers/projects.js"
    "controllers/matrix.js"
    "controllers/pipeline-data.js"
    "controllers/pipeline-data-en.js"
    "controllers/pipeline-data-vi.js"
    "controllers/pipeline-render.js"
    "controllers/pipeline.js"
    "main.js"
)

# Header
echo "/**" > "$OUTPUT"
echo " * bundle.js - Auto-generated single-file build (no import/export, no server needed)" >> "$OUTPUT"
echo " * Offline-friendly: works from file:// protocol on any modern browser." >> "$OUTPUT"
echo " *" >> "$OUTPUT"
echo " * DO NOT EDIT THIS FILE DIRECTLY. Edit source modules in src/bundle/ and" >> "$OUTPUT"
echo " * regenerate by running: bash src/bundle/build.sh" >> "$OUTPUT"
echo " */" >> "$OUTPUT"
echo "" >> "$OUTPUT"

total_lines=0

for mod in "${MODULES[@]}"; do
    mod_path="$SRC_DIR/$mod"
    if [ ! -f "$mod_path" ]; then
        echo "Module not found: $mod_path"
        exit 1
    fi
    
    line_count=$(wc -l < "$mod_path")
    total_lines=$((total_lines + line_count))
    
    echo "// ============================================================" >> "$OUTPUT"
    echo "// Source: src/bundle/$mod ($line_count lines)" >> "$OUTPUT"
    echo "// ============================================================" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    cat "$mod_path" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
done

echo "// ============================================================" >> "$OUTPUT"
echo "// End of bundle.js ($total_lines total lines from ${#MODULES[@]} modules)" >> "$OUTPUT"
echo "// ============================================================" >> "$OUTPUT"

echo "bundle.js generated: $OUTPUT ($total_lines lines from ${#MODULES[@]} modules)"
